name: Credit Fraud CI

on:
  push:
    paths:
      - "models/**"
      - "src/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: credit_fraud_detection
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Tests
        shell: bash -l {0}
        run: pytest tests/ --disable-warnings -v --cov=src
